FROM node:latest

# Install the npm packages
ADD package.json /
RUN npm install

EXPOSE 3000

# Change Directories
WORKDIR /app/

# On regular docker run execute the npm start command
CMD [ "npm", "start"]
